name: challenge8
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 상태 관리
  provider: ^6.0.0
  
  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  
  # 소셜 로그인
  google_sign_in: ^6.1.6
  
  # 파일 처리
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # UI
  flutter_quill: 10.8.5
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
