// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUDkobCYgT8KWO74_S5HKMLP1435LxRaw',
    appId: '1:864192977046:android:05919ac93cf0beaa8c8ab7',
    messagingSenderId: '864192977046',
    projectId: 'challenge8-note-app',
    storageBucket: 'challenge8-note-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO_gn89bxquwY7y8eMsXhYglX1Y0V5ag4',
    appId: '1:864192977046:ios:30f1c1de889b98148c8ab7',
    messagingSenderId: '864192977046',
    projectId: 'challenge8-note-app',
    storageBucket: 'challenge8-note-app.firebasestorage.app',
    iosClientId: '864192977046-81g6bgvvq1sv53domlnj7tfcnqdn7l9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.challenge8',
  );
}